### ISSUE TITLE
Something won't work here

### ISSUE THREAD

**Issue by mzanibelli** [JulienPradet/.dotfiles#1]
https://github.com/JulienPradet/.dotfiles/blob/97393f34e81c0256b1e0adad1a769556c2374954/install.sh#L3
``` suggestion
echo "blacklist pcspkr" | sudo tee /etc/modprobe.d/nobeep.conf
```

**Comment by JulienPradet** [comment]
Ah! J'avais pas vu. Je vais corriger ça, merci :)
